server:
  server.port: 8858
spring:
  datasource:
    username: root
    password: duyuming
    url: jdbc:mysql://localhost:3306/record?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver